# Generated by Django 5.0.6 on 2026-08-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, help_text='e.g. $90,000 - $110,000 or negotiable', max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='wishlist', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('software', 'Software Engineering'), ('data', 'Data / AI / ML'), ('design', 'Design'), ('product', 'Product Management'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_datetime', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Call'), ('onsite', 'Onsite / In-Person'), ('technical', 'Technical / Coding'), ('hr', 'HR Round'), ('final', 'Final Round'), ('other', 'Other')], default='video', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication')),
            ],
            options={
                'ordering': ['interview_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated or newline list')),
                ('required_experience', models.CharField(blank=True, max_length=255)),
                ('important_technologies', models.TextField(blank=True)),
                ('interview_prep_suggestions', models.TextField(blank=True)),
                ('match_score', models.PositiveIntegerField(blank=True, help_text='0-100 match with user profile', null=True)),
                ('raw_response', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='jobs.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='applications', to='jobs.tag'),
        ),
    ]
